export const siteKeywordsArray  = [
    "YouTube Playlist Analyzer",
    "Video Speed",
    "Binge-Watching",
    "Playlist Duration",
    "YouTube Playlist Length",
    "Playlist Length Calculator",
    "Video Length Analyzer",
    "Playback Speed Calculator",
    "YouTube Video Length",
    "Playlist Time Calculator",
    "Video Time Calculator",
    "YouTube Playlist Time",
    "Binge Watching Calculator",
    "Video Speed Calculator",
    "Playlist Duration Calculator",
    "YouTube Video Speed",
    "Video Length Calculator",
    "Playlist Analyzer Tool",
    "YouTube Playlist Analyzer Tool",
    "Video Playback Speed",
    "Playlist Length Tool",
    "YouTube Video Length Tool",
    "Video Time Analyzer",
    "Playlist Time Analyzer",
    "YouTube Playlist Length Tool",
    "Video Speed Analyzer",
    "Playlist Duration Analyzer",
    "YouTube Video Duration",
    "Playlist Length Analyzer",
    "Video Length Tool",
    "YouTube Playlist Duration",
    "Binge Watching Time Calculator",
    "Video Playback Time Calculator",
    "YouTube Video Playback Time",
    "Playlist Length Calculator Tool",
    "Video Speed Calculator Tool",
    "YouTube Playlist Length Calculator",
    "Video Time Calculator Tool",
    "Playlist Duration Calculator Tool",
    "YouTube Video Length Calculator",
    "Video Playback Speed Calculator Tool",
    "YouTube Playlist Time Calculator",
    "Binge Watching Calculator Tool",
    "Video Length Analyzer Tool",
    "Playlist Time Analyzer Tool",
    "YouTube Playlist Analyzer Online",
    "Video Speed Analyzer Tool",
    "Playlist Duration Analyzer Tool",
    "YouTube Video Duration Calculator",
    "Playlist Length Analyzer Online",
    "Video Length Calculator Online",
    "YouTube Playlist Duration Calculator",
    "Binge Watching Time Calculator Online",
    "Video Playback Time Calculator Online",
    "YouTube Video Playback Time Calculator",
  ]
export const socialMediaIconWithLinks = [
  {
    label: "LinkedIn",
    link: "https://www.linkedin.com/in/amar-tripathi/",
  },
  {
    label: "Github",
    link: "https://github.com/amartripathi0",
  },
  {
    label: "Email",
    link: "mailto:theamartripathi@gmail.com",
  },
];
