export const siteKeywordsArray = [
  "YouTube Playlist Analyzer",
  "Playlist Duration Calculator",
  "YouTube Watch Time Calculator",
  "Video Length Analyzer",
  "YouTube Playlist Length",
  "Playlist Time Calculator",
  "Video Speed Savings",
  "YouTube Course Length",
  "Playlist Binge Watch Calculator",
  "YouTube Analytics Tool",
  "Playlist Watch Time Estimator",
  "YouTube Playlist Checker",
  "Video Playback Duration",
  "YouTube Learning Productivity",
  "Playlist Efficiency Tool",
  "Total Playlist Runtime",
  "YouTube Video Speed Calculator",
  "How long is this YouTube playlist",
  "YouTube playlist time at 1.5x",
  "YouTube playlist time at 2x",
  "Playlist length checker",
  "YouTube productivity tools",
  "Video watch time analyzer",
  "YouTube study tracker",
  "Course completion calculator",
  "YouTube playlist stats",
  "Video playback speed savings",
  "YouTube learning optimizer",
  "Playlist duration at different speeds",
  "YouTube playlist time saver",
  "YouTube binge watch tracker",
  "Playlist length calculator online",
  "Free YouTube playlist tools",
  "YouTube API playlist analyzer",
  "Professional YouTube analytics online",
  "YouTube playlist length chrome extension alternative",
  "YouTube watch hours calculator",
  "Playlist length for YouTube courses",
  "Video time saver calculator",
  "YouTube learning accelerator",
  "YouTube playlist audit tool",
  "Video duration comparison tool",
  "YouTube playlist time management",
  "Watch time optimization tools",
  "YouTube creator productivity",
  "Playlist length analyzer 2026",
  "Best YouTube playlist calculator",
  "YouTube playlist time calculator free",
  "Analyze YouTube playlist duration fast",
  "YouTube playlist watch time insights",
];
export const socialMediaIconWithLinks = [
  {
    label: "Twitter",
    link: "https://twitter.com/amartripathi_",
  },
  {
    label: "LinkedIn",
    link: "https://www.linkedin.com/in/amar-tripathi/",
  },
  {
    label: "Github",
    link: "https://github.com/amartripathi0",
  },
  {
    label: "Email",
    link: "mailto:theamartripathi@gmail.com",
  },
];
